=== Blackjack200/Ouranos/src/main/resources/schema/nbt_upgrade_schema_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false,
			"properties": {
				"int": {
					"type": "integer"
				},
				"string": {
					"type": "string"
				},
				"byte": {
					"type": "integer"
				}
			}
		},
		"flattenRule": {
			"type": "object",
			"required": [
				"prefix",
				"flattenedProperty",
				"suffix"
			],
			"properties": {
				"prefix": {
					"type": "string"
				},
				"flattenedProperty": {
					"type": "string"
				},
				"flattenedPropertyType": {
					"type": "string",
					"enum": ["int", "string", "byte"]
				},
				"suffix": {
					"type": "string"
				},
				"flattenedValueRemaps": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				}
			},
			"additionalProperties": false
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minimum": 0
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					},
					"additionalProperties": false
				}
			}
		},
		"flattenedProperties": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/$defs/flattenRule"
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"required": [
						"oldState",
						"newState"
					],
					"oneOf": [
						{
							"required": ["newName"]
						},
						{
							"required": ["newFlattenedName"]
						}
					],
					"properties": {
						"oldState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newName": {
							"type": "string"
						},
						"newFlattenedName": {
							"$ref": "#/$defs/flattenRule"
						},
						"newState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"copiedState": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"additionalProperties": false
				}
			}
		}
	}
}

=== Blackjack200/Ouranos/src/main/resources/block_schema/nbt_upgrade_schema/0261_1.20.60.26_beta_to_1.20.70.24_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 20,
    "maxVersionPatch": 70,
    "maxVersionRevision": 4,
    "renamedIds": {
        "minecraft:grass": "minecraft:grass_block"
    },
    "flattenedProperties": {
        "minecraft:double_wooden_slab": {
            "prefix": "minecraft:",
            "flattenedProperty": "wood_type",
            "suffix": "_double_slab"
        },
        "minecraft:leaves": {
            "prefix": "minecraft:",
            "flattenedProperty": "old_leaf_type",
            "suffix": "_leaves"
        },
        "minecraft:leaves2": {
            "prefix": "minecraft:",
            "flattenedProperty": "new_leaf_type",
            "suffix": "_leaves"
        },
        "minecraft:wooden_slab": {
            "prefix": "minecraft:",
            "flattenedProperty": "wood_type",
            "suffix": "_slab"
        }
    },
    "remappedStates": {
        "minecraft:wood": [
            {
                "oldState": {
                    "stripped_bit": {
                        "byte": 0
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "wood_type",
                    "suffix": "_wood"
                },
                "newState": null,
                "copiedState": [
                    "pillar_axis"
                ]
            },
            {
                "oldState": {
                    "stripped_bit": {
                        "byte": 1
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:stripped_",
                    "flattenedProperty": "wood_type",
                    "suffix": "_wood"
                },
                "newState": null,
                "copiedState": [
                    "pillar_axis"
                ]
            }
        ]
    }
}

=== Blackjack200/Ouranos/src/main/resources/block_schema/nbt_upgrade_schema/0241_1.20.40.24_beta_to_1.20.50.23_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 20,
    "maxVersionPatch": 50,
    "maxVersionRevision": 1,
    "flattenedProperties": {
        "minecraft:planks": {
            "prefix": "minecraft:",
            "flattenedProperty": "wood_type",
            "suffix": "_planks"
        },
        "minecraft:stone": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_type",
            "suffix": "",
            "flattenedValueRemaps": {
                "andesite_smooth": "polished_andesite",
                "diorite_smooth": "polished_diorite",
                "granite_smooth": "polished_granite"
            }
        }
    }
}

=== Blackjack200/Ouranos/src/main/resources/upgrade_block/nbt_upgrade_schema/0311_1.21.30.24_beta_to_1.21.40.25_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 21,
    "maxVersionPatch": 40,
    "maxVersionRevision": 1,
    "renamedIds": {
        "minecraft:skull": "minecraft:skeleton_skull"
    },
    "removedProperties": {
        "minecraft:cherry_wood": [
            "stripped_bit"
        ],
        "minecraft:mangrove_wood": [
            "stripped_bit"
        ]
    },
    "remappedStates": {
        "minecraft:brown_mushroom_block": [
            {
                "oldState": {
                    "huge_mushroom_bits": {
                        "int": 10
                    }
                },
                "newName": "minecraft:mushroom_stem",
                "newState": null,
                "copiedState": [
                    "huge_mushroom_bits"
                ]
            },
            {
                "oldState": {
                    "huge_mushroom_bits": {
                        "int": 15
                    }
                },
                "newName": "minecraft:mushroom_stem",
                "newState": null,
                "copiedState": [
                    "huge_mushroom_bits"
                ]
            },
            {
                "oldState": null,
                "newName": "minecraft:brown_mushroom_block",
                "newState": null,
                "copiedState": [
                    "huge_mushroom_bits"
                ]
            }
        ],
        "minecraft:red_mushroom_block": [
            {
                "oldState": {
                    "huge_mushroom_bits": {
                        "int": 10
                    }
                },
                "newName": "minecraft:mushroom_stem",
                "newState": null,
                "copiedState": [
                    "huge_mushroom_bits"
                ]
            },
            {
                "oldState": {
                    "huge_mushroom_bits": {
                        "int": 15
                    }
                },
                "newName": "minecraft:mushroom_stem",
                "newState": null,
                "copiedState": [
                    "huge_mushroom_bits"
                ]
            },
            {
                "oldState": null,
                "newName": "minecraft:red_mushroom_block",
                "newState": null,
                "copiedState": [
                    "huge_mushroom_bits"
                ]
            }
        ]
    }
}

=== Blackjack200/Ouranos/src/main/resources/upgrade_block/nbt_upgrade_schema/0181_1.19.70_to_1.19.80.24_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 19,
    "maxVersionPatch": 80,
    "maxVersionRevision": 11,
    "flattenedProperties": {
        "minecraft:fence": {
            "prefix": "minecraft:",
            "flattenedProperty": "wood_type",
            "suffix": "_fence"
        },
        "minecraft:log": {
            "prefix": "minecraft:",
            "flattenedProperty": "old_log_type",
            "suffix": "_log"
        },
        "minecraft:log2": {
            "prefix": "minecraft:",
            "flattenedProperty": "new_log_type",
            "suffix": "_log"
        }
    }
}

=== Blackjack200/Ouranos/src/main/resources/upgrade_block/nbt_upgrade_schema/0171_1.19.60_to_1.19.70.26_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 19,
    "maxVersionPatch": 70,
    "maxVersionRevision": 15,
    "flattenedProperties": {
        "minecraft:wool": {
            "prefix": "minecraft:",
            "flattenedProperty": "color",
            "suffix": "_wool",
            "flattenedValueRemaps": {
                "silver": "light_gray"
            }
        }
    }
}

=== Blackjack200/Ouranos/src/main/resources/block_schema/nbt_upgrade_schema/0271_1.20.70.24_beta_to_1.20.80.24_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 20,
    "maxVersionPatch": 80,
    "maxVersionRevision": 3,
    "removedProperties": {
        "minecraft:bamboo_sapling": [
            "sapling_type"
        ]
    },
    "flattenedProperties": {
        "minecraft:coral_fan": {
            "prefix": "minecraft:",
            "flattenedProperty": "coral_color",
            "suffix": "_coral_fan",
            "flattenedValueRemaps": {
                "blue": "tube",
                "pink": "brain",
                "purple": "bubble",
                "red": "fire",
                "yellow": "horn"
            }
        },
        "minecraft:coral_fan_dead": {
            "prefix": "minecraft:dead_",
            "flattenedProperty": "coral_color",
            "suffix": "_coral_fan",
            "flattenedValueRemaps": {
                "blue": "tube",
                "pink": "brain",
                "purple": "bubble",
                "red": "fire",
                "yellow": "horn"
            }
        },
        "minecraft:red_flower": {
            "prefix": "minecraft:",
            "flattenedProperty": "flower_type",
            "suffix": "",
            "flattenedValueRemaps": {
                "houstonia": "azure_bluet",
                "orchid": "blue_orchid",
                "oxeye": "oxeye_daisy",
                "tulip_orange": "orange_tulip",
                "tulip_pink": "pink_tulip",
                "tulip_red": "red_tulip",
                "tulip_white": "white_tulip"
            }
        },
        "minecraft:sapling": {
            "prefix": "minecraft:",
            "flattenedProperty": "sapling_type",
            "suffix": "_sapling"
        }
    }
}

=== Blackjack200/Ouranos/src/main/resources/block_schema/nbt_upgrade_schema/0251_1.20.50.23_beta_to_1.20.60.26_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 20,
    "maxVersionPatch": 60,
    "maxVersionRevision": 1,
    "flattenedProperties": {
        "minecraft:hard_stained_glass": {
            "prefix": "minecraft:hard_",
            "flattenedProperty": "color",
            "suffix": "_stained_glass",
            "flattenedValueRemaps": {
                "silver": "light_gray"
            }
        },
        "minecraft:hard_stained_glass_pane": {
            "prefix": "minecraft:hard_",
            "flattenedProperty": "color",
            "suffix": "_stained_glass_pane",
            "flattenedValueRemaps": {
                "silver": "light_gray"
            }
        }
    }
}

=== Blackjack200/Ouranos/src/main/resources/block_schema/nbt_upgrade_schema/0291_1.21.0.25_beta_to_1.21.20.24_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 21,
    "maxVersionPatch": 20,
    "maxVersionRevision": 6,
    "renamedIds": {
        "minecraft:yellow_flower": "minecraft:dandelion"
    },
    "removedProperties": {
        "minecraft:coral_fan_hang3": [
            "coral_hang_type_bit"
        ]
    },
    "flattenedProperties": {
        "minecraft:anvil": {
            "prefix": "minecraft:",
            "flattenedProperty": "damage",
            "suffix": "anvil",
            "flattenedValueRemaps": {
                "broken": "deprecated_",
                "slightly_damaged": "chipped_",
                "undamaged": "",
                "very_damaged": "damaged_"
            }
        },
        "minecraft:coral_fan_hang3": {
            "prefix": "minecraft:",
            "flattenedProperty": "dead_bit",
            "flattenedPropertyType": "byte",
            "suffix": "horn_coral_wall_fan",
            "flattenedValueRemaps": {
                "0": "",
                "1": "dead_",
                "dummy": "map_not_list"
            }
        },
        "minecraft:dirt": {
            "prefix": "minecraft:",
            "flattenedProperty": "dirt_type",
            "suffix": "dirt",
            "flattenedValueRemaps": {
                "coarse": "coarse_",
                "normal": ""
            }
        },
        "minecraft:double_stone_block_slab": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type",
            "suffix": "_double_slab",
            "flattenedValueRemaps": {
                "wood": "petrified_oak"
            }
        },
        "minecraft:double_stone_block_slab2": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type_2",
            "suffix": "_double_slab",
            "flattenedValueRemaps": {
                "prismarine_dark": "dark_prismarine",
                "prismarine_rough": "prismarine"
            }
        },
        "minecraft:double_stone_block_slab3": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type_3",
            "suffix": "_double_slab"
        },
        "minecraft:double_stone_block_slab4": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type_4",
            "suffix": "_double_slab",
            "flattenedValueRemaps": {
                "stone": "normal_stone"
            }
        },
        "minecraft:light_block": {
            "prefix": "minecraft:light_block_",
            "flattenedProperty": "block_light_level",
            "flattenedPropertyType": "int",
            "suffix": ""
        },
        "minecraft:monster_egg": {
            "prefix": "minecraft:infested_",
            "flattenedProperty": "monster_egg_stone_type",
            "suffix": "",
            "flattenedValueRemaps": {
                "chiseled_stone_brick": "chiseled_stone_bricks",
                "cracked_stone_brick": "cracked_stone_bricks",
                "mossy_stone_brick": "mossy_stone_bricks",
                "stone_brick": "stone_bricks"
            }
        },
        "minecraft:prismarine": {
            "prefix": "minecraft:",
            "flattenedProperty": "prismarine_block_type",
            "suffix": "",
            "flattenedValueRemaps": {
                "bricks": "prismarine_bricks",
                "dark": "dark_prismarine",
                "default": "prismarine"
            }
        },
        "minecraft:quartz_block": {
            "prefix": "minecraft:",
            "flattenedProperty": "chisel_type",
            "suffix": "",
            "flattenedValueRemaps": {
                "chiseled": "chiseled_quartz_block",
                "default": "quartz_block",
                "lines": "quartz_pillar",
                "smooth": "smooth_quartz"
            }
        },
        "minecraft:red_sandstone": {
            "prefix": "minecraft:",
            "flattenedProperty": "sand_stone_type",
            "suffix": "red_sandstone",
            "flattenedValueRemaps": {
                "cut": "cut_",
                "default": "",
                "heiroglyphs": "chiseled_",
                "smooth": "smooth_"
            }
        },
        "minecraft:sand": {
            "prefix": "minecraft:",
            "flattenedProperty": "sand_type",
            "suffix": "sand",
            "flattenedValueRemaps": {
                "normal": "",
                "red": "red_"
            }
        },
        "minecraft:sandstone": {
            "prefix": "minecraft:",
            "flattenedProperty": "sand_stone_type",
            "suffix": "sandstone",
            "flattenedValueRemaps": {
                "cut": "cut_",
                "default": "",
                "heiroglyphs": "chiseled_",
                "smooth": "smooth_"
            }
        },
        "minecraft:stone_block_slab2": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type_2",
            "suffix": "_slab",
            "flattenedValueRemaps": {
                "prismarine_dark": "dark_prismarine",
                "prismarine_rough": "prismarine"
            }
        },
        "minecraft:stone_block_slab3": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type_3",
            "suffix": "_slab"
        },
        "minecraft:stone_block_slab4": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_slab_type_4",
            "suffix": "_slab",
            "flattenedValueRemaps": {
                "stone": "normal_stone"
            }
        },
        "minecraft:stonebrick": {
            "prefix": "minecraft:",
            "flattenedProperty": "stone_brick_type",
            "suffix": "stone_bricks",
            "flattenedValueRemaps": {
                "chiseled": "chiseled_",
                "cracked": "cracked_",
                "default": "",
                "mossy": "mossy_",
                "smooth": ""
            }
        }
    },
    "remappedStates": {
        "minecraft:coral_fan_hang": [
            {
                "oldState": {
                    "dead_bit": {
                        "byte": 0
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "coral_hang_type_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "_coral_wall_fan",
                    "flattenedValueRemaps": {
                        "0": "tube",
                        "1": "brain",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "coral_direction"
                ]
            },
            {
                "oldState": {
                    "dead_bit": {
                        "byte": 1
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:dead_",
                    "flattenedProperty": "coral_hang_type_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "_coral_wall_fan",
                    "flattenedValueRemaps": {
                        "0": "tube",
                        "1": "brain",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "coral_direction"
                ]
            }
        ],
        "minecraft:coral_fan_hang2": [
            {
                "oldState": {
                    "dead_bit": {
                        "byte": 0
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "coral_hang_type_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "e_coral_wall_fan",
                    "flattenedValueRemaps": {
                        "0": "bubbl",
                        "1": "fir",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "coral_direction"
                ]
            },
            {
                "oldState": {
                    "dead_bit": {
                        "byte": 1
                    }
                },
                "newFlattenedName": {
                    "prefix": "minecraft:dead_",
                    "flattenedProperty": "coral_hang_type_bit",
                    "flattenedPropertyType": "byte",
                    "suffix": "e_coral_wall_fan",
                    "flattenedValueRemaps": {
                        "0": "bubbl",
                        "1": "fir",
                        "dummy": "map_not_list"
                    }
                },
                "newState": null,
                "copiedState": [
                    "coral_direction"
                ]
            }
        ]
    }
}
